Fix `RLock` incompatibility when using`spawn` (#228)
* remove missing overwrite from `overviews`

* Create `RLock` using the `spawn` context

Should fix the error:

RuntimeError: A SemLock created in a fork context is being shared with a process
in a spawn context. This is not supported. Please use the same context to create
multiprocessing objects and Process.

* change return value of `displacement` compressed slcs to list of `Path`s

* fix single disp test