Compute residuals to the timeseries inversion, save to raster outputs (#523)
* Add `censored_lstsq` to solve least squares with missing data

* Put conncomp file list first

* [skip ci] remove dup line

* Fix `invert_unw_stack` to set output pixel `nodata` based on unw nodata

* start writing residuals to a raster

* Fix bug in gdal overview threadd lzw creation

When doing `GDAL_NUM_THREADS=2` and LZW, this came up
  File "/Users/staniewi/repos/dolphin/src/dolphin/_overviews.py", line 95, in create_image_overviews
    ds.BuildOverviews(resampling.value, levels)
  File "/Users/staniewi/miniforge3/envs/mapping-312/lib/python3.12/site-packages/osgeo/gdal.py", line 4378, in BuildOverviews
    return _gdal.Dataset_BuildOverviews(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: /vsimem/decompress_0x312935528.tif:Using code not yet in table

After turning the python multithreading off, and the GDAL_NUM_THREADS=1,
it was still giving this:

RuntimeError: 20210606_20210618.tif, band 1: IReadBlock failed at X offset 0, Y offset 2: TIFFReadEncodedTile() failed.
May be caused by: TIFFReadEncodedTile() failed.
May be caused by: /Users/staniewi/repos/dolphin/docs/notebooks/work-walkthrough/timeseries/20210606_20210618.tif:Using code not yet in table

This was on a Mac with Gdal 3.9.0
$ gdalinfo --version
GDAL 3.9.3, released 2024/10/07

* Add a `set_raster_nodata` to match the `get_`

* add missing io tests

* Fix occasional sorting issue for residuals, nodata outputs

* remove extra utils import

* Get residuals per date working

* fix overview by setting nodata value in `GA_Update` mode

* setup residual path tests, add to workflows and `extra_reference` logic

* fix tests

* fix last resid path problem