disable corrections pytest
This is very annoying to get working with fake data.
The current error is:
RuntimeError: The -tr option was used, but there's no geotransform or it is
rotated.  This configuration is not supported.

The geometdata for statis layers is wrong