Disable corrections part of pytest, add one for timeseries (#254)
* dont exit before unwrapping for full test

* make test data have mostly signal, not pure noise

* fix the failing test due to len 1 stack losing dimension

* raise an error if the reference point selection fails

* fix 3d writing, pytest gets farther

* `max_bandwidth` can be 1: fix `gt` pydantic restriction

* try more

* disable corrections pytest

This is very annoying to get working with fake data.
The current error is:
RuntimeError: The -tr option was used, but there's no geotransform or it is
rotated.  This configuration is not supported.

The geometdata for statis layers is wrong

* fix jax warning

* [skip ci] fix changelog date